{% set version = "1.0.9" %}

package:
  name: mako
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/M/Mako/Mako-{{ version }}.tar.gz
  sha256: 0728c404877cd4ca72c409c0ea372dc5f3b53fa1ad2bb434e1d216c0444ff1fd

build:
  number: 0
  preserve_egg_dir: True
  entry_points:
    - mako-render=mako.cmd:cmdline
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - markupsafe >=0.9.2

test:
  imports:
    - mako
    - mako.ext
  commands:
    - mako-render --help

about:
  home: http://www.makotemplates.org/
  license_file: LICENSE
  license: MIT
  summary: A super-fast templating language that borrows the best ideas from the existing templating languages.
  doc_url: http://docs.makotemplates.org/en/latest/
  dev_url: https://bitbucket.org/zzzeek/mako/src

extra:
  recipe-maintainers:
    - Korijn
    - pmlandwehr
