travis:
  secure:
    BINSTAR_TOKEN: RNlDWp33qjJZcSm2SewjyiXvyMtq3y6FSAMrVRiVL9plwa+4AFUvEddcCAq2EZ/KDBxpfCZ/E+3WQobWMVMBwsDEbhqrpedIYkvkMV5HPmw8/Wh6cx38p7Dq30yMpOXMtyKFZHqjBz8e+BWre8uZlTxh5GmMZ5uPtL0WymerOWaG+ljfV9uQz0ihU8fK0Ddp2KBt8QhVA8qECVEIP7PaUlM3JnaNWAgFE68sPERINI4o3hOmsD7nHzF4mZkW6/aT70FvrYcyf0Cv04slEZ/SRdwaYtoV4C35WGzvNdobEDnt+JmzQ98fhzMlcHjB78OMhghatwYQrokkDQeiIJbsoVKdLhlGIaI1RVhvtK5JNzX4K0chZ2IdVMSSXT6DlzWp2ou2qmeKHWsKT341Zz6YcPSfC8TU8ya2vvlTaF5pAn4fBuOrlK6fCwpWJoLepxzl5GcY8mukPCX1J1TeIXKuKTWhz0iNA2awNm7qFDmT+l4vaJNOREtRQlTguDhTOW8TrBYJlxQqVk9d8384F+1qei47bJ4NXbP/X5l7jiTNwLKzZ0kxurK/BSKxsEni5Lwd6EK2mwheHx/BzxjZKEIRQEHNhxrVnB69iZD7JhPKkhqbRkIhNu8W5zZuWsdV3BygWJLpDrdm6k9gi7UgLLKA+x2wNsIlF9vKjtdYdjf7DTs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
