travis:
  secure:
    BINSTAR_TOKEN: on5LxqVc1A1WIxNSCKSffw13tJCJkZwzjaFv8WSTsB6nLNTfp7kN4Dfj0UG4/WRbR5iplGBkUaqjirD1xVwl+RYsiVFF8AI4gIFIPMHMUEVbsC/RVJdq0YowU/NdMwdRWLXwRlwPejCPPpeYpRPovxe/r7KhOLChTcAdml8uhlm0lCZR7MYoLa6HDpd4zso++/kWmbyUdcJSPwTqusgXIWN8wnC1BqRpY7xVI+WvaSb4wgvelvYZCCyW970hmO7tx/Zo+xYtMsmhYIQZiZwh0rW7iQHLs2i0TBV9YA22IUutHFiAiSuTyv9CFi9yVmckwI0a8jeRHg5C0bLX8QuupYEns0/cefN+nOfAFtIhwOwF6DEwEjWI9Fv0GK5QftL9EOlJVuq2gADes5qLwXuPLo9fn2p/yVQE50vBKgXGPfm1T3fAe4MCmeHHHZA70XyrfjSvCUwq4R5AnEGEKBji5zHgFX2AKcHdkDVHnYAXpOyCY75TprmQtELmoJq5BpT6Xj36fxkwQ5Z7I6PAXBfdbC8s1qpJFW9PODsGhYmFEEZBHKsq/6bfj8FrQMcbES6NOpDfySZzqWO6CPkWtv6dzGIyJhnW7I2UGupqJtgUFosirxelQtRsE2/IJNdmyZhl40AE7UZH7cWMgWVxBd45ctkzRf5naqhAEsCncyDoAXk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
